### ISSUE TITLE
Boletos: tela

### ISSUE THREAD

**Issue by luizpiovesana** [mauro0x52/eekit#106]
Caso seja possível deixar os dados da conta gravados, o ideal é que o menu esquerdo tenha dois ícones:
1- Boletos (vai para lista)
2- Contas (pode ser integrado com o do Financeiro)

Dentro do "Boletos" ele visualiza a lista (de acordo com a issue) e também tem o botão "criar novo boleto".
E o equivalente para a parte de contas, onde ele pode editar as existentes ou adicionar novas.

**Comment by mauro0x52** [comment]
Escopo muito trolha. WONTFIX por enquanto.
