### ISSUE TITLE
Adicionar transação sem categoria

### ISSUE THREAD

**Issue by mauro0x52** [mauro0x52/eekit#109]
Quando um usuário tenta cadastrar uma receita ou uma despesa sem ainda ter cadastrado alguma categoria, dá para cadastrar mas a transação não aparece.

**Comment by rerthal** [comment]
não estou conseguindo reproduzir o bug

**Comment by millor** [comment]
Pra testar é só apagar todas as categorias e ver se aparece modal "Você precisa ter categorias e contas cadastradas"? 

Se for isso, dá pra dar close já, pq testei e funfou
