### ISSUE TITLE
Lista de usuários e e-mails

### ISSUE THREAD

**Issue by millor** [mauro0x52/eekit#111]
A página http://empreendekit.com.br:8001/users?secret=tracker está dando a seguinte mensagem de erro:
{
  "error": {
    "message": "service unauthorized",
    "name": "InvalidServiceError",
    "path": "service"
  }
}

**Comment by rerthal** [comment]
agora o endereço para busca será:
:8003/users

**Comment by millor** [comment]
Funfando em Pelúcio. Coloquei tag "testar no ar"
