### ISSUE TITLE
Enviar email para usuário recém cadastrado

### ISSUE THREAD

**Issue by mauro0x52** [mauro0x52/eekit#116]
Enviar o seguinte email para o usuário que acabou de se cadastrar:
## 

Olá _NOME_, tudo bom?

Você se cadastrou no Empreendekit e acabou de dar o primeiro passo para se tornar sua empresa mais produtiva.

Para te ajudar nessa jornada, estou te enviando um ebook que acabamos de lançar: "Produtividade sem Enrolação".
Para baixar gratuitamente o ebook, clique aqui.

Qualquer dúvida sobre o Empreendekit, pode mandar um email direto pra mim.

Abraços,

Gabriel
## 

Link: http://pages.rdstation.com.br/livro-produtividade?utm_source=Etapa2&utm_medium=Email-semana2&utm_content=Contatos-poscadastro&utm_campaign=LC02

**Comment by mauro0x52** [comment]
Testa saporra ae @lucashoogerbrugge

**Comment by lucashoogerbrugge** [comment]
Não chegou @mauro0x52

**Comment by mauro0x52** [comment]
Testa aew @lucashoogerbrugge

**Comment by lucashoogerbrugge** [comment]
Não chegou =/ @mauro0x52

**Comment by lucashoogerbrugge** [comment]
Mentira... Chegou sim =)
