### ISSUE TITLE
Valor do boleto antigo após editar valor da transação

### ISSUE THREAD

**Issue by mineirocosta** [mauro0x52/eekit#12]
Ao editar o valor da transação por dentro dela (através da expansão) e tentar gerar um boleto, o valor preenchido no modal aparece no valor antigo.

Pra reproduzir o bug:
- Cria uma transação e de termina um valor (ex: 20 reais)
- Clica na transação para abrir mais detalhes 
- Clica em editar e muda o valor da transação (ex: 30 reais)
- Clica em gerar o boleto

Bug: O valor que aparece é o de 20 reais

**Comment by mauro0x52** [comment]
Mineiro, coloque nomes melhores nos títulos, tipo esse que botei.
