### ISSUE TITLE
Nome do responsável sobrepondo calendário expandido

### ISSUE THREAD

**Issue by luizpiovesana** [mauro0x52/eekit#126]
É o mesmo problema que surgiu quando o campo de categoria passou a ser o scroll-down. 

![image](https://f.cloud.github.com/assets/3373012/339323/f260986e-9d33-11e2-92c9-1af6f0ed3bad.png)

**Comment by millor** [comment]
Ainda pega um pedacinho, mas melhorou bastante. Estou aceitando.

![Captura de Tela 2013-04-10 a s 16 17 11](https://f.cloud.github.com/assets/3328307/364009/452b7ac6-a213-11e2-9d11-a14b38fcdaa8.png)
