### ISSUE TITLE
Log do usuário no tracker não carrega

### ISSUE THREAD

**Issue by lucashoogerbrugge** [mauro0x52/eekit#127]
O novo userlog no tracker não está carregando.

Ex:.http://support.empreendekit.com.br:8003/user/515d7f5b5dfb9f1c0b000024/events/

**Comment by mauro0x52** [comment]
Testa no ar @lucashoogerbrugge

**Comment by lucashoogerbrugge** [comment]
Continua o mesmo erro @mauro0x52
