### ISSUE TITLE
Lista de usuários no tracker abre a página mas da erro

### ISSUE THREAD

**Issue by lucashoogerbrugge** [mauro0x52/eekit#128]
Ao abrir http://support.empreendekit.com.br:8003/users/ me retorna o erro:
"TypeError: Failed to parse JSON body: Cannot read property '_id' of null"

**Comment by mauro0x52** [comment]
Testa no ar @lucashoogerbrugge

**Comment by mauro0x52** [comment]
@lucashoogerbrugge testa e fecha isso para não ficar poluindo o github.

**Comment by lucashoogerbrugge** [comment]
Continua o mesmo erro @mauro0x52
