### ISSUE TITLE
Erro ao gerar boleto

### ISSUE THREAD

**Issue by mineirocosta** [mauro0x52/eekit#13]
Ao tentar preencher com os seguintes dados abaixo (1), aparece a mensagem (2) no seguinte link (3).

(1)------ Dados que preenchi ------

![dados](https://f.cloud.github.com/assets/3636775/193187/f51b2234-7f7b-11e2-96a1-c0efeab211b2.png)

(2)------ Mensagem de erro: ------
{
  "error": {
    "message": "Validation failed",
    "name": "ValidationError",
    "errors": {
      "wallet": {
        "message": "Validator \"enum\" failed for path wallet",
        "name": "ValidatorError",
        "path": "wallet",
        "type": "enum"
      }
    }
  }
}

(3) ------ Link gerado: ------
http://empreendemia.no-ip.org:8009/billet?receiver=564564564564&cpfCnpj=12.345.678/0001-00&bankId=341&agency=1619&account=36921&accountVD=6&wallet=52&agreement=&value=10,00&creationDate=Mon%20Feb%2025%202013%2000:00:00%20GMT-0300%20(Hora%20oficial%20do%20Brasil)&dueDate=Tue%20Feb%2026%202013%2000:00:00%20GMT-0300%20(Hora%20oficial%20do%20Brasil)&clientName=Fulano%20de%20Tal&demonstrative=&instructions=N%C3%A3o%20aceitar%20ap%C3%B3s%20o%20vencimento.

**Comment by mauro0x52** [comment]
Coloquei um select box para diminuir as chances do cara botar uma carteira inválida.
