### ISSUE TITLE
Tarefas marcadas como feita não aparecendo no "Tarefas feitas"

### ISSUE THREAD

**Issue by luizpiovesana** [mauro0x52/eekit#131]
Aconteceu na sexta-feira pelo menos com Luiz e Millor, com tarefas importantes e não-importantes nas categorias: geral, vendas e finanças (pelo menos).
-- não conseguimos reproduzir erro.

**Comment by rerthal** [comment]
Para a solução desse bug um padrão deve ser encontrado, para tal, uma validação cruzada do tarefas deve ser criada, ou seja, todos os dados do tarefas devem se colocados em uma planilha excel e e sempre que um dado for modificado, a planilha também deve ser modificada, a fim de detectarmos o padrão do bug
