### ISSUE TITLE
Tarefas editadas e remarcadas para outros dias retornaram para o dia original

### ISSUE THREAD

**Issue by luizpiovesana** [mauro0x52/eekit#132]
Hoje (sexta) de manhã eu editei diversas tarefas, alterando alguns nomes, mas o que mudei em todas foram as datas.

À tarde, essas tarefas cujas datas tinham sido alteradas, retornaram como tarefas pendentes do dia.
-- eu as remarquei para frente, vamos ver o que acontece.

**Comment by rerthal** [comment]
Para a solução desse bug um padrão deve ser encontrado, para tal, uma validação cruzada do tarefas deve ser criada, ou seja, todos os dados do tarefas devem se colocados em uma planilha excel e e sempre que um dado for modificado, a planilha também deve ser modificada, a fim de detectarmos o padrão do bug
