### ISSUE TITLE
Alterações dashboard Tarefas

### ISSUE THREAD

**Issue by millor** [mauro0x52/eekit#140]
Como admin gostaria de mudar um pouco os parâmetros usados na análise do comportamento dos usuários do Tarefas
- Dentro de ativação, colocar o número de usuários com 1 ocorrência do evento "clicar: adicionar tarefa" como 1a coluna
- Mudar o critério de ativação para 1 ocorrência do evento "marcar tarefa como feita"
- Remover a coluna "Marcaram 3 tarefas como feitas" da etapa de ativação
- Mudar o critério de engajamento de 5 para 3 ocorrências do evento "marcar tarefa como feita"

Obs.: Essa parte do "marcar tarefa como feita" não tinha sido previsto na conversa, mas Lucas comentou que isso ajudará nas análises. Como imagino que não seja muito complicado, adicionei na tarefa

**Comment by rerthal** [comment]
Mudo também o critério de ativação no lifecycle?

**Comment by millor** [comment]
Precisa confirmar com Lucas, mas imagino que sim.

 http://empreendemia.com.br/e/empreendemia/pessoas/19112010
Millor Machado http://empreendemia.com.br/e/empreendemia/pessoas/19112010
Diretor de estratégia para a desenrolação do empreendedorismo brasileiro

 empreendemia.com.br http://www.empreendemia.com.br - a rede de empresas
para acelerar seus negócios
 saiadolugar.com.br http://www.saiadolugar.com.br - dicas para o
empreendedor que não tem tempo a perder
"Minha vida é um livro abertis!" - Antônio Carlos Bernardes Gomes

**Comment by lucashoogerbrugge** [comment]
Muda...

Quer que remodele lá?
 http://www.empreendemia.com.br/e/empreendemia/pessoas/19125175
Lucas Hoogerbruggehttp://www.empreendemia.com.br/e/empreendemia/pessoas/19125175
Gerente de Marketing de Relacionamento com Terráqueos
Celular (tim): (19) 8177-5725
Escritório:      (11) 3230-9233
 empreendemia.com.br http://www.empreendemia.com.br/ - a rede de empresas
para acelerar seus negócios
 saiadolugar.com.br http://www.saiadolugar.com.br/ - dicas para o
empreendedor que não tem tempo a perder
"My name is Bond, James Bond." - James Bond

Em 10 de abril de 2013 11:53, millor notifications@github.com escreveu:

> Precisa confirmar com Lucas, mas imagino que sim.
> 
> http://empreendemia.com.br/e/empreendemia/pessoas/19112010
> Millor Machado http://empreendemia.com.br/e/empreendemia/pessoas/19112010
> 
> Diretor de estratégia para a desenrolação do empreendedorismo brasileiro
> 
> empreendemia.com.br http://www.empreendemia.com.br - a rede de empresas
> para acelerar seus negócios
> saiadolugar.com.br http://www.saiadolugar.com.br - dicas para o
> empreendedor que não tem tempo a perder
> "Minha vida é um livro abertis!" - Antônio Carlos Bernardes Gomes
> 
> On Wed, Apr 10, 2013 at 11:49 AM, Rafael Almeida Erthal Hermano <
