### ISSUE TITLE
Melhorar visibilidade do click da entidade em uma lista

### ISSUE THREAD

**Issue by millor** [mauro0x52/eekit#155]
Como usuário gostaria de ver de forma mais intuitiva que posso clicar em uma entidade para poder usar mais funcionalidades do sistema

Obs.: É necessário criar wireframe sobre como ficará essa funcionalidade

**Comment by mauro0x52** [comment]
WONTFIX: a solução exige reestruturação do HTML e CSS, como enviado nos emails.
