### ISSUE TITLE
Tarefas: Tarefa com recorrência diária na 6a-feira

### ISSUE THREAD

**Issue by millor** [mauro0x52/eekit#16]
Como usuário gostaria que uma tarefa com recorrência diária marcada como feita na 6a fosse jogada para a 2a ao invés do sábado

**Comment by mauro0x52** [comment]
Não é bug. E tem gente que trabalha de sábado.

**Comment by rerthal** [comment]
A solução mudou, agora teremos duas opções, uma para todos os dias e outra para dias da semana preciso de melhor modelagem para continuar
