### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by mauro0x52** [mauro0x52/eekit#173]
```
                                           *******PRINCIPAL*******
```

Home
- 4 abas principais: Principal, Planos, Como Funciona, Dúvidas
- Título: Ferramenta de gestão para microempresários
- Subtítulo: Simples. Rápido. Barato.
- Imagem: Print screen 
- Botão: Experimente grátis por 15 dias (leva menos de 30 segundos) - (link para www.empreendekit.com.br/#!/ee/cadastro)
- Abaixo do botão: "Saiba mais" (link: www.empreendekit.com.br/#!/ee/como-funciona)
## ![wireframe_home](https://f.cloud.github.com/assets/3636775/392629/ff5a205e-a782-11e2-9854-3518cd338e6c.png)

```
                                           *******PLANOS*******
```

www.empreendekit.com.br/#!/ee/precos-e-planos

Plano 1 mês
Subtítulo: Só para começar
Preço: R$59/mês (sem ,00 mesmo)
Textos:
1 - Até 5 usuários
2 - Ferramentas: Cuide de seus contatos; Organize suas tarefas, Gerencie suas finanças
3 - Suporte básico

Plano 3 meses
Subtítulo: Mais popular
Preço: R$54/mês (sem ,00 mesmo)
Textos: 
1 - Até 5 usuários
2 - Ferramentas: Cuide de seus contatos; Organize suas tarefas, Gerencie suas finanças
3 - Suporte personalizado (destaque no personalizado)

Plano 6 meses
Subtítulo: Cliente VIP
Preço: R$49/mês (sem ,00 mesmo)
Textos: 
1 - Até 5 usuários
2 - Ferramentas: Cuide de seus contatos; Organize suas tarefas, Gerencie suas finanças
3 - Suporte personalizado (destaque no personalizado)

Texto inferior: "Está com dúvidas? Converse agora com a gente por email (contato@empreendekit.com.br) ou telefone (11 3230-9233)"
Obs1: "agora" destacado
Obs2: email tem link 
Obs3: chat online tem link. 

**_PÁGINA PARA USUÁRIO DESLOGADO**_
- Sem botões de assinar nos planos 
- Botão: Experimente grátis por 15 dias (link para www.empreendekit.com.br/#!/ee/cadastro)
- "grátis" destacado
- Botão experimente grátis redireciona para página de cadastro (ou modal)

![wireframe_deslogado](https://f.cloud.github.com/assets/3636775/387440/3476b03a-a6c1-11e2-9673-2551960f60eb.png)

---

```
                                       *******CADASTRO*******
```
- Cadastre para testar gratuitamente por 15 dias
- Tudo simples e sem compromisso!
- Campos de cadastro (Nome, Empresa, Telefone, Email, Senha)
- Textos com informações de segurança:
  Texto 1: 
  Seus dados estão seguros
  Nós nos preocupamos com a sua segurança e garantimos que suas informações são confidenciais

Texto 2: 
Não vamos te pedir dados de pagamento
Se você não quiser mais usar após o teste, não será cobrado!

Texto 3:
Tudo online, sem downloads
É só cadastrar e usar. Não precisa instalar nada. Simples assim!

![wireframe_cadastro](https://f.cloud.github.com/assets/3636775/393171/2b7da8a0-a791-11e2-9bc3-04aeb5f64342.png)

```
                                       *******COMO FUNCIONA*******
```

www.empreendekit.com.br/#!/ee/como-funciona

Título principal: O sistema de gestão para microempresas mais simples da internet
Texto: O EmpreendeKit é a mais simples ferramenta online de gestão para microempresários.
Em um só lugar você consegue controlar de forma rápida e fácil tudo o que precisa no dia-a-dia da sua empresa. 
O principal objetivo é economizar tempo na gestão, para investir seu tempo no que realmente importa: Vender mais e crescer o seu negócio.
Aqui todos os nossos clientes são especiais e fazemos questão de dar um suporte personalizado.

Título 1: Gerencie o prazo das tarefas dos seus clientes
Texto subtítulo 1: Adicione tarefas para cada cliente, assim não perde o prazo das atividades que tem que entregar.

Título 2: Suas finanças sem complicação
Texto subtítulo 2: Faça o básico bem feito:
                             \* Registre suas vendas
                             \* Controle seu fluxo de caixa
                             \* Emita boletos

Título 3: Lembre-se do que tem que ser feito
Texto subtítulo 3: Receba lembretes por email de suas tarefas e transações. 
Dessa forma você nunca mais vai esquecer de ligar para um cliente, fazer um relatório ou pagar uma conta.

Título 4: Tarefas, clientes e finanças. Tudo isso integrado.
Texto subtítulo 4: Todas as ferramentas são integradas, isso significa que é possível adicionar tarefas e transações em um contato e adicionar lembretes em uma conta. 
Você pode gerenciar tudo da sua empresa em um só lugar. Simples. Rápido. Fácil.

Título 5: Sua equipe trabalhando junta
Subtítulo 5: Sistema para até 5 usuários, onde tudo pode ser compartilhado. Tarefas, clientes e finanças.

Botão: Experimente grátis por 15 dias (leva menos de 30 segundos) - (link para www.empreendekit.com.br/#!/ee/cadastro)

![wireframe_comofunciona](https://f.cloud.github.com/assets/3636775/387626/e2fef03c-a6c5-11e2-90f2-2c2ac0eb4c6a.png)

---

```
                                              *******SUPORTE*******
```

www.empreendekit.com.br/#!/ee/suporte
- FAQ (quando clica na pergunta, expande resposta)
- Ajuda e suporte
- Botão: Skype - ligar via skype
- Indicação do chat online

**_Ajuda e suporte**_
Oferecemos suporte gratuito por e-mail e telefone a todos nossos usuários
Se você tiver dúvidas ou problemas, fique à vontade para entrar em contato conosco pelo e-mail contato@empreendekit.com.br ou pelo nosso telefone (11)3230-9233

**_FAQ**_
- Como funciona?
  O objetivo do Empreendekit é simplificar a gestão das microempresas. Atualmente o Empreendekit conta com três ferramentas para cuidar das finanças, clientes e tarefas.
  Você pode ver mais informações na página Como Funciona (link: www.empreendekit.com.br/#!/ee/como-funciona)
  Se você quiser saber se o Empreendekit funcionará bem na sua empresa, você pode testar gratuitamente (link: www.empreendekit.com.br/#!/ee/cadastro) ou conversar conosco por chat ou skype.
- Quanto custa?
  A ferramenta custa R$59,00 por mês. Entretanto, esse preço diminui nos planos trimestral e semestral. Veja mais nossos preços e planos (link para a página: www.empreendekit.com.br/#!/ee/precos-e-planos).
- Como pago?
  O pagamento pode ser feito através do Pagseguro, com cartão de crédito ou boleto.
  Você pode acessar nossos preços e planos (link: www.empreendekit.com.br/#!/ee/precos-e-planos). 
- Tem alguma fidelidade no contrato?
  Não. Você pode cancelar a qualquer momento.
- Outras pessoas da minha empresa podem usar?
  Sim! Até 5 pessoas da sua empresa podem usar. As tarefas, contatos e finanças podem ser compartilhadas.
- Tenho que instalar alguma coisa?
  Não! Toda a ferramenta é online e você pode acessar de qualquer computador.
- Os meus dados estão seguros?
  Sim!
- Existe alguma forma de fazer backup dos meus dados?
  Sim! Você pode exportar seus dados financeiros ou de clientes e guardar com você.
- E se eu tiver dificuldades para usar?
  Esperamos que você não tenha. Mas se tiver, estamos aqui para te ajudar. Podemos marcar um horário para conversar e te ajudamos a configurar e usar a ferramenta.
- Existe suporte para a ferramenta?
  Sim! Se você precisar de ajuda para configurar ou tirar duas dúvidas, você tem suporte por email, telefone, skype ou chat online com a gente.

![wireframe_suporte](https://f.cloud.github.com/assets/3636775/391355/7b387d44-a763-11e2-97f3-1021d1ddc349.png)

**Comment by millor** [comment]
Por onde acesso essa home?

**Comment by mauro0x52** [comment]
MVP o FAQ colapsável foi pro beleleu.
