### ISSUE TITLE
Orientador para mudar nome do arquivo ao exportar dados no Contatos

### ISSUE THREAD

**Issue by lucashoogerbrugge** [mauro0x52/eekit#192]
Mensagem:
Para abrir os dados exportados é necessário renomear o arquivo com o final ".csv"
Ex:. download.csv

Regra: Clicar no botão "baixar dados" no Contatos
Posição do balão: Embaixo do botão de baixar dados

**Comment by rerthal** [comment]
Uma outra solução foi abordada, simplesmente exibir no browser o csv
