### ISSUE TITLE
Orientador para mudar nome do arquivo ao exportar dados no Finanças

### ISSUE THREAD

**Issue by lucashoogerbrugge** [mauro0x52/eekit#193]
Mensagem:
Para abrir os dados exportados é necessário renomear o arquivo com o final ".csv"
Ex:. download.csv

Regra: Clicar no botão "baixar dados" no Finanças
Posição do balão: Embaixo do botão de baixar dados

**Comment by rerthal** [comment]
Uma outra solução foi abordada, simplesmente exibir no browser o csv

**Comment by millor** [comment]
Esse e o "Contatos" tá baixando o arquivo sem extensão da mesma forma que era antes. Não veio .csv
