### ISSUE TITLE
Chat nas páginas de venda e suporte

### ISSUE THREAD

**Issue by mineirocosta** [mauro0x52/eekit#196]
**Label da janela do chat:** "Chat online - Estamos disponíveis"

**Mensagens durante o uso do chat:**
-  Quando usuário ou atendente estão escrevendo mensagem: "está escrevendo..."
- Quando usuário ou atendente sai da conversa: "O atendente/usuário saiu da conversa."
- Se atendente fica offline: "Não estamos online agora. Mande um email para contato@empreendekit.com.br ou nos adicione no skype: empreendemia"

**Onde aparece o janela do chat**
_\- ee/home_
- Chat apenas fica disponível na página, NÃO sobe sozinho
- Mensagem quando o usuário clica no chat: "Olá, tudo bem? Posso te ajudar com alguma coisa?"

_\- ee/cadastro_
- Chat fica disponível na página e abre depois de 15 segundos.
- Mensagem de início: "Olá, tudo bem? Está com alguma dúvida no cadastro?"

_\- ee/precos-e-planos_
- Chat fica disponível na página e abre depois de 15 segundos OU quando clica no link "chat online" no texto da página
- Mensagem de início: "Olá, tudo bem? O que achou dos nossos planos?"

_\- ee/como-funciona_
- Chat fica disponível na página e abre depois de 15 segundos.
- Mensagem de início: "Olá, tudo bem? Posso te ajudar em alguma coisa?"

_\- ee/suporte_
- Chat já está aberto quando usuário entra na página
- Mensagem de início: "Olá, tudo bem? Como posso te ajudar?"

_\- /pagamento-1mes; /pagamento-3meses; /pagamento-6meses;_
- Chat abre quando usuário clica no chat OU quando clica no link "chat online" no texto da página
- Mensagem de início: "Olá, tudo bem? Posso te ajudar em alguma coisa?"

**Atendimento**
_O que atendente visualiza:_
- link com log do usuário no tracker (logado ou deslogado)

_Regras de atendimento_:
- Existe apenas 1 atendente: contato@empreendekit.com.br
- O atendente pode atender até 3 usuários ao mesmo tempo
- Se o atendente está totalmente ocupado (3 atendimentos simultâneos), chat não fica mais disponível
- Se o atendente está totalmente ocupado (3 atendimentos simultâneos) e alguém tenta iniciar um novo chat, abre janela do chat com a seguinte mensagem: "Os atendentes estão ocupados, mas não se preocupe! Mande um email para contato@empreendekit.com.br ou tente de novo daqui uns minutos."

**Conta a ser usada**
_Atendente:_ contato@empreendekit.com.br

_Usuários fantasmas_
eekittalk1@gmail.com
eekittalk2@gmail.com
eekittalk3@gmail.com
_pssw_: kawasakitalk

![chat1](https://f.cloud.github.com/assets/3636775/403171/55e9cb74-a916-11e2-8d1f-f59a799b8baa.png)

![chat2](https://f.cloud.github.com/assets/3636775/403173/59a73616-a916-11e2-807e-be36fce62afe.png)

**Comment by rerthal** [comment]
Quando o chat abrir automaticamente após os 15 segundos em
- ee/cadastro
- ee/precos-e-planos
- ee/como-funciona
- ee/suporte
- /pagamento-1mes; /pagamento-3meses; /pagamento-6meses

uma conta fantasma terá que ser alocada para o visitante, portanto, uma das três conversas possiveis será gasta com o cliente.

Outra coisa, caso não tenha atendente disponível, mesmo assim a janela deve abrir após os 15 segundos e exibir a mensagem "Os atendentes estão ocupados, mas não se preocupe! Mande um email para contato@empreendekit.com.br ou tente de novo daqui uns minutos." ?

Caso algum atendente fique vago após os 15 segundos o chat deve abrir?

A mensagem "Não estamos online agora. Mande um email para contato@empreendekit.com.br ou nos adicione no skype: empreendemia" deve ser exibida no corpo do chat ou no cabeçalho?

**Comment by mineirocosta** [comment]
Se todos os atendentes estão ocupados, não abre o chat automaticamente.
Se todos os atendentes estão ocupados e alguém inicia o chat, abre chat com mensagem de indisponível.

Mensagem de indisponível aparece no corpo do chat.

**Comment by rerthal** [comment]
Caso o usuário ja tenha aberto o chat, se ele mudar de janela o chat continua ativo?
Caso o chat tenha aberto automaticamente e o usuário nao digitar nada a janela continua aberta caso o usuário mude de página?

Qual o critério para desalocar o atendente?
Por exemplo: Usuário entra na tela de cadastro, o chat aparece e o usuário larga o navegador aberto e vai fazer outras coisas, o atendente deve ficar alocado para esse usuário?

**Comment by mineirocosta** [comment]
Se usuário está com chat aberto e muda de janela, o chat continua ativo.

Se o chat abre e o usuário não digita nada em 60 segundos, chat fecha e desaloca atendente.

**Comment by rerthal** [comment]
Vamos supor o seguinte caso de uso:

usuário vai na tela ee/como-funciona
=> no chat irá aparecer a mensagem: "Olá, tudo bem? Posso te ajudar em alguma coisa?"

o usuário não responde nada, em seguida, o usuário vai para a tela - ee/precos-e-planos
=> no chat irá aparecer a mensagem: "Olá, tudo bem? O que achou dos nossos planos?"

a mensagem antiga "Olá, tudo bem? Posso te ajudar em alguma coisa?" permanece no histórico ou sai do corpo do chat?

Outro cenário:

usuário vai na tela ee/como-funciona
=> no chat irá aparecer a mensagem: "Olá, tudo bem? Posso te ajudar em alguma coisa?"

o usuário interage com o atendente, em seguida, o usuário vai para a tela  - ee/precos-e-planos
O chat deve manter o histórico da conversa anterior? O sistema deve mesmo assim exibir automaticamente a mensagem "Olá, tudo bem? O que achou dos nossos planos?" ?

**Comment by mineirocosta** [comment]
Se usuário troca de página em menos de 1 minuto, o chat permanece aberto, com a nova mensagem logo depois da antiga e a contagem de 1 minuto reinicia.

Se usuário interage com atendente depois vai pra tela preços e planos, o chat mantém histórico da conversa anterior e exibe automaticamente a mensagem "Olá, tudo bem? O que achou dos nossos planos?"

**Comment by rerthal** [comment]
Seria esse diagrama de atividades?
![chat](https://f.cloud.github.com/assets/1065773/606414/f0ed5848-cd29-11e2-9a8d-a6467be6bbf8.png)

**Comment by mineirocosta** [comment]
Acho que sim. Só fiquei com uma dúvida olhando o diagrama.

A partir do momento que o chat está ativo (usuário escreve alguma coisa), só desaloca o atendente quando o usuário fecha o chat ou o navegador. Certo?
Ex: Se no meio da conversa o usuário fica sem falar nada por 10 minutos, o atendente continua alocado.

Se for isso (e isso for mais fácil), acho que pode ficar assim mesmo.

**Comment by mauro0x52** [comment]
Abortamos o sistema próprio, estamos usando o Zopim.
Sem essa de abrir 15s depois. Nessas páginas ele abre direto, mas apenas uma vez.
