### ISSUE TITLE
Registrar eventos da nova Home

### ISSUE THREAD

**Issue by lucashoogerbrugge** [mauro0x52/eekit#199]
Como admin gostaria de saber o ciclo de uso do usuário na rede, para saber a eficácia de cada parte e onde os usuários clicam mais.
- Disparar evento "visualizar: principal" quando o usuário visualizar a página www.empreendekit.com.br/#!/ee/principal
- Disparar evento "visualizar: cadastro" quando o usuário visualizar a página www.empreendekit.com.br/#!/ee/cadastro
- Disparar eventos quando o usuário fizer os seguintes eventos na página de cadastro
  - Nome - cadastrar: nome
  - Empresa - cadastrar: empresa
  - Telefone - cadastrar: telefone
  - E-mail - cadastrar: e-mail
  - Senha - cadastrar: senha
  - Finalizou cadastro - cadastrar
- Disparar evento "visualizar: como funciona" quando o usuário visualizar a página www.empreendekit.com.br/#!/ee/como-funciona
- Disparar evento "visualizar: precos-e-planos" quando o usuário visualizar a página www.empreendekit.com.br/#!/ee/precos-e-planos
- Disparar evento "visualizar: suporte" quando o usuário visualizar a página www.empreendekit.com.br/#!/ee/suporte

Os eventos de auth e onboarding para frente (eventos disparados dentro dos apps) continuam iguais.

**Comment by mauro0x52** [comment]
Só para manter padrão, mudei o "visualizar: como funciona" para "visualizar: como-funciona"
