### ISSUE TITLE
Contacts - Mudar critérios ativação/engajamento/retenção

### ISSUE THREAD

**Issue by lucashoogerbrugge** [mauro0x52/eekit#201]
Ativação
- Adicionou 1 contato

Engajamento
- Adicionou 3 contatos ou adicionou 1 tarefa ou adicionou 1 transação ou editou 1 contato

Retenção
- Disparou o evento "visualizar: contatos" na semana

Essas mudanças se aplicam para a ficha do usuário, dashboard e para os emails de LifeCycle

Como vai ficar:
Aquisição
- Novos usuários do app

Ativação
- Começaram a adicionar contato (clicar: adicionar contato)
- Adicionaram 1 contato

Engajamento
- Adicionou 3 contatos ou adicionou 1 tarefa ou adicionou 1 transação ou editou 1 contato

**Comment by millor** [comment]
A princípio seria o mesmo critério de engajamento para a retenção, mas vimos que seria inviável o cálculo para cada semana. Transformamos então o critério em simplesmente o usuário acessar o app

**Comment by lucashoogerbrugge** [comment]
Não consegui reproduzir retenção no cohort do contatos
