### ISSUE TITLE
Seleção da data com problemas

### ISSUE THREAD

**Issue by luizpiovesana** [mauro0x52/eekit#21]
Ao inserir ou editar uma tarefa, a escolha de data não acontece no primeiro clique -- preciso clicar entre 2 e 4 vezes para que a seleção do dia realmente ocorra.

**Comment by mauro0x52** [comment]
Acabei fazendo merda e isso foi para o ar.

**Comment by luizpiovesana** [comment]
Ficou de boa agora o/
