### ISSUE TITLE
Tooltip nas ações

### ISSUE THREAD

**Issue by mauro0x52** [mauro0x52/eekit#23]
Colocar tooltip padrão nas ações e no menu

**Comment by mauro0x52** [comment]
Acabei fazendo merda e isso foi para o ar.

**Comment by luizpiovesana** [comment]
Tarefas e Finanças funcionando de boa.

No Contatos só apareceu tooltip do menu esquerdo e da parte superior (baixar dados e adicionar contato).
Não apareceu nenhum tooltip de ação da lista:
1- Adicionar contato nesta categoria (no +)
2- Mover contato
3- Editar contato
4- Excluir contato

**Comment by luizpiovesana** [comment]
Tá ok no pelúcio. Falta só o deploy.
