### ISSUE TITLE
Erro ao tentar gerar boleto do Itau

### ISSUE THREAD

**Issue by lucashoogerbrugge** [mauro0x52/eekit#231]
Quando tento gerar um boleto na carteira 175 do Itau, me volta o seguinte erro:

Cannot GET /billet?receiver=Empreendemia&amp;cpfCnpj=10.679.087/0001-29&amp;bankId=341&amp;agency=1619&amp;account=33538&amp;accountVD=1&amp;wallet=175&amp;agreement=&amp;value=60.00&amp;creationDate=Tue%20May%2007%202013%2000:00:00%20GMT-0300%20(Hora%20oficial%20do%20Brasil)&amp;dueDate=Fri%20May%2010%202013%2000:00:00%20GMT-0300%20(Hora%20oficial%20do%20Brasil)&amp;clientName=Onfire&amp;demonstrative=Premium&amp;instructions=N%C3%A3o%20aceitar%20ap%C3%B3s%20o%20vencimento.

**Comment by millor** [comment]
Também tinha visto esse erro pré-deploy. Com novo app de boletos está funcionando direitinho. Vou fechar a issue
