### ISSUE TITLE
Usuário escutando todos os eventos

### ISSUE THREAD

**Issue by mauro0x52** [mauro0x52/eekit#234]
Um usuário está ouvindo os eventos de todos os outros usuários online, mesmo sendo de outras empresas.

Um usuário só pode ouvir usuários da mesma empresa.

**Comment by millor** [comment]
Aparentemente isso só tem impacto ao visualizar uma lista embedada. Na lista normal de tarefas, por exemplo, não aparece nada de outro usuário

**Comment by millor** [comment]
Continua não funcionando.

Caso de uso em Pelúcio:
1 - Logo como vai@ee.com no Chrome e van@ee.com no Firefox. Eles são de empresas diferentes.
2 - Vou para a ficha de um contato com os 2 usuários
3 - Adiciono uma tarefa relacionada a um contato pelo Vai
4 - A tarefa só aparece para o Vai depois de F5
5 - A tarefa aparece na lista de tarefas do contato do Van
