### ISSUE TITLE
Exibir log de usuário identificado pelo ip

### ISSUE THREAD

**Issue by millor** [mauro0x52/eekit#236]
Como admin gostaria de ver a lista de eventos associadas a um ip para poder identificá-lo

**Comment by rerthal** [comment]
quando digitar o ip do usuario na url, substituir os "." por "_"
ex: 127_0_0_1

**Comment by millor** [comment]
Quando clicamos em um usuário listado em algum dashboard ele coloca na URL com o '.'. Facilita muito se já abrir com o '_'. Isso entra nessa feature ou é melhor criar outra específica pra esse caso de uso?
