### ISSUE TITLE
Associar ip a um usuário

### ISSUE THREAD

**Issue by millor** [mauro0x52/eekit#237]
Como admin gostaria de associar um ip a um user-id para poder identificá-lo

/user/associate?secret=tr4ck3r&ip=ip-do-usuário&id=id-do-usuário

**Comment by millor** [comment]
Rafael,
Confere por favor se é esse mesmo o comando. Qualquer coisa já edita na issue.

**Comment by rerthal** [comment]
esse mesmo

**Comment by millor** [comment]
Sintaxe é:
http://support.empreendekit.com.br:8003/user/associate?secret=tr4ck3r&ip=187.104.159.110&user=517e885ac7697cf272000089

Com destaque do ip ter que ser '.' e user ao invés de id
