### ISSUE TITLE
Mover com filtro ligado no Contatos

### ISSUE THREAD

**Issue by luizpiovesana** [mauro0x52/eekit#239]
Ao filtrar determinadas categorias de contatos no Contatos e tentar mover (enquanto estou com o Filtro ligado), os contatos que não deveriam aparecer surgem de volta.

Porém, depois de mover para o lugar certo, o que não está filtrado some novamente.

**Comment by millor** [comment]
Ainda precisamos modelar certinho quais serão as regras, enquanto isso se mantém de backlog.
