### ISSUE TITLE
Tarefa recorrente marcada como feita aparece na lista embedada de outros usuários

### ISSUE THREAD

**Issue by millor** [mauro0x52/eekit#242]
Caso de uso:
- Usuário A marca tarefa recorrente como feita
- Usuário A vê nova tarefa criada no prazo definido pela recorrência
- Usuário B vê nova tarefa em lista de tarefas embedadas de um contato

**Comment by luizpiovesana** [comment]
Está também acontecendo quando:
- Usuário A está com entidade (contato1) aberta
- Usuário B edita tarefa do usuário A (de outro contato, ou seja, contato2)
- Usuário A visualiza tarefa do contato2 na entidade aberta do contato1
