### ISSUE TITLE
Ficha de usuário não está aparecendo para usuários que estão com IP em vez de ID

### ISSUE THREAD

**Issue by lucashoogerbrugge** [mauro0x52/eekit#245]
Ao tentar acessar os usuários que estão aparecendo com o IP no Dashboard do WWW, me aparece o seguinte erro:
{ "error": { "message": "Cast to ObjectId failed for value \"177_18_201_211\" at path \"user\"", "name": "CastError", "type": "ObjectId", "value": "177_18_201_211", "path": "user" } }

**Comment by rerthal** [comment]
Posso fechar?

**Comment by millor** [comment]
Testei em Pelúcio e tá supimposo. To fechando a Issue
