### ISSUE TITLE
Boleto da Caixa não funciona

### ISSUE THREAD

**Issue by luizpiovesana** [mauro0x52/eekit#246]
Fizemos um teste para boleto da Caixa e o cedente (Carlos da HH) não recebeu o pagamento.

Segue aqui o boleto que o Carlos gerava:
![image](https://f.cloud.github.com/assets/3373012/519343/761e287c-bf14-11e2-8154-befb65df9237.png)

Um ponto que percebi no sistema atual é que não rola colocar dígito no código do cedente da Caixa (que é um número que sempre tá lá).

Um número a mais que existe na Caixa é o "código de operação" -- mas pelo o que vi do Carlos, ele nunca colocou esse número no sistema da Superlógica. Porém, acho que é esse número no boleto do Carlos "870" que fica entre a agência e o código do cedente.

**Comment by mauro0x52** [comment]
Rancamo fora, junto com o BB.
