### ISSUE TITLE
Usuários inserindo o "R$" dentro do campo "valor" no modal de transação

### ISSUE THREAD

**Issue by luizpiovesana** [mauro0x52/eekit#247]
Como usuário, gostaria de ver que o campo de valor não precisa que eu inclua o "R$" na mão; Ou que, ao escrevê-lo no campo, não dê problema na inserção da transação.

Na prática, 3 usuários que eu vi mexendo por skype colocaram o "R$" dentro do campo do valor, o que fez com que desse como "valor inválido".
Soluções que pensei:
1- O campo se chamar "Valor: R$"
2- O sistema aceitar quando alguém coloca R$, U$ etc.

**Comment by rerthal** [comment]
o fato do sistema ja informar que o campo está inválido ja é suficiente para evitar bugs...
