### ISSUE TITLE
Modal de inserção de boleto (por dentro do Finanças) não cabendo na página

### ISSUE THREAD

**Issue by luizpiovesana** [mauro0x52/eekit#248]
Ao ver usuários emitindo boletos pelo Finanças e pelo Boletos, notei que em 2 casos (todos que vi) o modal estava muito grande e o botão do final "enviar" (que é o que cria o boleto de fato) não aparece na tela e também não há a opção de scroll pra chegar lá.

Não sei se foram configurações estranhas que vi, mas aconteceu nos dois casos -- não tenho uma sugestão de solução ainda.

**Comment by rerthal** [comment]
o modal agora tem scrollbar
