### ISSUE TITLE
Email de relatório de tarefas

### ISSUE THREAD

**Issue by mineirocosta** [mauro0x52/eekit#249]
Email de relatório de atividades pendentes semanais

**Regras para envio de emails**

Usuário que fez login na semana anterior recebe email

Regra discutida 
Se usuário cadastrou tarefa na semana -> semana seguinte recebe email de tarefas
Se usuário **não** cadastrou tarefa na semana -> recebe email se cadastrou na semana passada
Se usuário **não** cadastrou tarefa na semana -> recebe email se cadastrou na semana retrasada

_(caso tiver dúvida na regra, me chama)_

Horário de envio dos emails:  (06:30)

No caso de o usuário não haver tarefas cadastradas, aparece a seguinte mensagem: 
"Não há tarefas importantes cadastradas"

No caso de o usuário não haver tarefas cadastradas, aparece a seguinte mensagem: "Não há tarefas para esse dia"

---

**Email**
Assunto - Suas tarefas dessa semana

Texto: 

Olá _NOME_!

Este é um relatório automático de tarefas do Empreendekit. Você o receberá toda 2ª feira para poder organizar melhor sua semana.

_Tarefas importantes da semana:_
- Tarefa importante 1
- Tarefa importante 2
- Tarefa importante 3
- ...

_Outras tarefas:_

2a-feira:
- Tarefa 1
- Tarefa 2
- Tarefa 3

3a-feira:
- Tarefa 4

4a-feira:
- Tarefa 5
- Tarefa 6

5a-feira:
- Tarefa 7
- Tarefa 8
- Tarefa 9
- Tarefa 10

6a-feira:
_Nenhuma tarefa para esse dia_

Quer adicionar mais tarefas e organizar sua semana? Clique _aqui_ 

_link no aqui:_ http://www.empreendekit.com.br/?utm_source=eekit&utm_medium=email&utm_content=relatorio-tarefas&utm_campaign=lifecycle#!/tarefas

---

**Comment by mauro0x52** [comment]
Acho que vale a pena isso ir para o ar já sem o resto.

**Comment by mauro0x52** [comment]
Para testar, cria as tarefas com lembretes e pede para mim ou Rafael rodar o script do reminder.

**Comment by millor** [comment]
Considerando que o e-mail foi enviado hoje, pode fechar a Issue ou só amanhã pra ver se enviou sem rodar o script manualmente?
