### ISSUE TITLE
Email de Lifecycle Engajamento 1 - Tarefas (3)

### ISSUE THREAD

**Issue by mineirocosta** [mauro0x52/eekit#250]
Lifecycle  Engajamento 1 - Tarefas

**Regra para receber o email:**
*Usuário não engajado depois de 24h de ativar no app Tarefas
*Só recebe email se não tiver recebido: 
--Lifecycle  Engajamento 1 -  Contatos
--Lifecycle  Engajamento 1 -  Finanças

(futuramente usuário pagante não receberá esse email, mas essa regra ainda não se aplica)

**Source:** eekit
**Medium:** email
**Campaign:** lifecycle
**Content:** engajamento-1t
**Nome no sendgrid:** eekit lc engajamento 1t
**Responder para:** gabriel@empreendemia.com.br
**UTM:** http://www.empreendekit.com.br/?utm_source=eekit&utm_medium=email&utm_content=engajamento-1t&utm_campaign=lifecycle#!/tarefas

**Assunto:** Agora falta pouco para se tornar um mestre da produtividade!

**Conteúdo:** 
Olá _|FNAME|_, tudo bom?

Meus parabéns! Você já começou com o pé direito o uso do Empreendekit.

O próximo passo é se tornar um mestre da produtividade!
Para isso, adicione mais tarefas e não se esqueça de marcá-las como feitas. 
Medir seus avanços na semana é fundamental para aumentar sua produtividade.

Para acessar o EmpreendeKit, clique aqui.

Se tiver alguma dúvida, é só me mandar um email =)

Abraços,

Gabriel

**Comment by mauro0x52** [comment]
Alguns cortes:
- vai ser lucas quem vai mandar o email
- não vai rolar o critério se ele recebeu email dos lifecycles de contatos e finanças

**Comment by mauro0x52** [comment]
Não é mais empreendekit.com.br/#!/tarefas, é empreendekit.com.br/tarefas.

**Comment by mauro0x52** [comment]
Critérios alterados para:
- usuários ativos no tarefas há 1 dia
- usuários != ativos no contatos
- usuários != ativos no finanças
