### ISSUE TITLE
Email de Lifecycle Engajamento 1 - Contatos (2)

### ISSUE THREAD

**Issue by mineirocosta** [mauro0x52/eekit#251]
Lifecycle  Engajamento 1 - Contatos
- Usuário não engajado depois de 24h de ativar no app Contatos
- Só recebe email se não tiver recebido: 
  --Lifecycle  Engajamento 1 -  Finanças

(futuramente usuário pagante não receberá esse email, mas essa regra ainda não se aplica)

**Source:** eekit
**Medium:** email
**Campaign:** lifecycle
**Content:** engajamento-1c
**Nome no sendgrid:** eekit lc engajamento 1c
**Responder para:** gabriel@empreendemia.com.br
**UTM:** http://www.empreendekit.com.br/?utm_source=eekit&utm_medium=email&utm_content=engajamento-1c&utm_campaign=lifecycle#!/contatos

---

**Assunto:** Agora falta pouco para se tornar um mestre da produtividade!

**Conteúdo:** 
Olá _|FNAME|_, tudo bom?

Meus parabéns! Você já começou com o pé direito o uso do Empreendekit.

O próximo passo é se tornar um mestre da produtividade!
Para isso, adicione mais contatos e tarefas para cada um deles. 
Saber o que deve ser feito para cliente é fundamental para aumentar sua produtividade e vender mais.

Para acessar o EmpreendeKit, clique aqui.

Se tiver alguma dúvida, é só me mandar um email =)

Abraços,

Gabriel

**Comment by mauro0x52** [comment]
Lucas que envia emails

Critérios:
- usuário = ativo no contatos
- usuário != ativo no finanças
