### ISSUE TITLE
Email de Lifecycle Engajamento 1 - Finanças (1)

### ISSUE THREAD

**Issue by mineirocosta** [mauro0x52/eekit#252]
Lifecycle Engajamento 1 - Finanças

**Regra para receber o email:**
Usuário não engajado depois de 24h de ativar no app Finanças

(futuramente usuário pagante não receberá esse email, mas essa regra ainda não se aplica)

**Source:** eekit
**Medium:** email
**Campaign:** lifecycle
**Content:** engajamento-1f
**Nome no sendgrid:** eekit lc engajamento 1f
**Responder para:** gabriel@empreendemia.com.br
**UTM:** http://www.empreendekit.com.br/?utm_source=eekit&utm_medium=email&utm_content=engajamento-1f&utm_campaign=lifecycle#!/financas

**Assunto:**  Agora falta pouco para se tornar um mestre da produtividade!

*_Conteúdo: *_
Olá _|FNAME|_, tudo bom?

Meus parabéns! Você já começou com o pé direito o uso do Empreendekit.

O próximo passo é se tornar um mestre da produtividade!
Para isso, coloque as categorias de receitas e despesas mais adequadas para a rotina da sua empresa e adicione mais movimentações financeiras já com essas novas categorias.
Ter seu fluxo de caixa organizado é fundamental para controlar sua empresa e aumentar sua produtividade.

Para acessar o EmpreendeKit, clique aqui.

Se tiver alguma dúvida, é só me mandar um email =)

Abraços,

Gabriel

**Comment by mauro0x52** [comment]
Lucas quem vai enviar os emails
