### ISSUE TITLE
Atualizar emails 24h de Lifecycle

### ISSUE THREAD

**Issue by lucashoogerbrugge** [mauro0x52/eekit#253]
**_L.C. Ativação 1 - Email de 24h: Dicas práticas em bullets de como ativar no Tarefas**_
**Regra para receber o email:**
Usuário não ativado depois de 24h do cadastro
Não recebe o Email se for usuário pagante
Fez evento "Marcar: tarefas"

**Source:** eekit
**Medium:** email
**Campaign:** lifecycle
**Content:** ativacao-1t
**Nome no sendgrid:** eekit lc ativacao 1t
**Responder para:** lucas@empreendemia.com.br
**UTM:** http://www.empreendekit.com.br/?utm_source=eekit&utm_medium=email&utm_content=ativacao-1t&utm_campaign=lifecycle#!/tarefas

**Assunto:**  2 dicas fáceis para organizar as suas tarefas na empresa

**Conteúdo:**
Olá _|FNAME|_, tudo bom?

Bem vindo ao EmpreendeKit!
Para te ajudar a continuar organizando as suas tarefas, separei 2 dicas: 

1) adicione uma tarefa que você tem que fazer hoje
2) assim que terminar a tarefa, marque a tarefa como feita

Recomendo que faça isso para suas 3 principais tarefas. Você já vai ver a diferença!

Para acessar o EmpreendeKit e já aplicar as dicas, clique aqui(http://www.empreendekit.com.br/?utm_source=eekit&utm_medium=email&utm_content=ativacao-1t&utm_campaign=lifecycle#!/tarefas).

Abraços,
Lucas

**_L.C. Ativação 1 - Email de 24h: Dicas práticas em bullets de como ativar no Contatos**_
**Regra para receber o email:**
Usuário não ativado depois de 24h do cadastro
Não recebe o Email se for usuário pagante
Fez evento "Marcar: contatos"

**Source:** eekit
**Medium:** email
**Campaign:** lifecycle
**Content:** ativacao-1c
**Nome no sendgrid:** eekit lc ativacao 1c
**Responder para:** lucas@empreendemia.com.br
**UTM:** http://www.empreendekit.com.br/?utm_source=eekit&utm_medium=email&utm_content=ativacao-1c&utm_campaign=lifecycle#!/contatos

**Assunto:**  2 dicas fáceis para cuidar dos prazos de seus clientes

*_Conteúdo: *_
Olá _|FNAME|_, tudo bom?

Bem vindo ao Empreendekit!
Para te ajudar a continuar organizando as suas tarefas, separei 2 dicas: 

1) adicione um contato
2) adicione uma tarefa no contato

Recomendo que faça isso para seus 3 principais contatos. Você já vai ver a diferença!

Para acessar o EmpreendeKit e já aplicar as dicas, clique aqui(http://www.empreendekit.com.br/?utm_source=eekit&utm_medium=email&utm_content=ativacao-1c&utm_campaign=lifecycle#!/contatos).

Abraços,
Lucas

**_L.C. Ativação 1 - Email de 24h: Dicas práticas em bullets de como ativar no Finanças**_
**Regra para receber o email:** 
Usuário não ativado depois de 24h do cadastro
Não recebe o Email se for usuário pagante
Fez evento "Marcar: financas"

**Source:** eekit
**Medium:** email
**Campaign:** lifecycle
**Content:** ativacao-1f
**Nome no sendgrid:** eekit lc ativacao 1f
**Responder para:** lucas@empreendemia.com.br
**UTM:** http://www.empreendekit.com.br/?utm_source=eekit&utm_medium=email&utm_content=ativacao-1f&utm_campaign=lifecycle#!/financas

**Assunto:**  O ultimo passo para sair da planilha

*_Conteúdo: *_
Olá _|FNAME|_, tudo bom?

Bem vindo ao Empreendekit!
Para te ajudar a sair da planilha de excel, separei 2 dicas: 

1) Adicione as movimentações dessa próxima semana
2) Crie lembretes para as principais

Assim você não se preocupa em esquecer de fazer pagamentos ou cobranças e pode se dedicar mais a seus clientes.

Para acessar o EmpreendeKit e já aplicar as dicas, clique aqui(http://www.empreendekit.com.br/?utm_source=eekit&utm_medium=email&utm_content=ativacao-1f&utm_campaign=lifecycle#!/financas).

Abraços,
Lucas

**Comment by mauro0x52** [comment]
Não tem dessa de "se for usuário pagante não recebe".

**Comment by mauro0x52** [comment]
E não tem essa de "Olá Fulano de Tal", por enquanto vai sem nome do cara.

**Comment by lucashoogerbrugge** [comment]
Depois do dia 18, ninguém mais recebeu esse email.
