### ISSUE TITLE
Após inclusão ou edição de entidade, sistema não mostra a atualização

### ISSUE THREAD

**Issue by luizpiovesana** [mauro0x52/eekit#254]
Ao editar uma entidade na listagem, em alguns casos a atualização no sistema só ocorre após um F5.

Ao incluir uma entidade dentro de outra (tarefa dentro de contato), em alguns casos a atualização também não ocorre.
Em um caso específico, tentei adicionar uma tarefa por dentro do contato e nada ocorreu. Tentei marcar uma tarefa que estava lá aberta como 'feita' e nada. Fechei as abas, apertei F5 e estava tudo atualizado.

Ainda não encontrei um padrão maior que esse: a atualização das entidades nem sempre funciona antes de um F5.

**Comment by luizpiovesana** [comment]
Vi aqui também que às vezes o "marcar como feito" e o remover também não atualizam a lista de entidades na hora.

**Comment by mauro0x52** [comment]
@luizpiovesana  isso aqui ta rolando ainda?

**Comment by lucashoogerbrugge** [comment]
Ainda ta
 http://www.empreendemia.com.br/e/empreendemia/pessoas/19125175
Lucas Hoogerbruggehttp://www.empreendemia.com.br/e/empreendemia/pessoas/19125175
Gerente de Marketing de Relacionamento com Terráqueos
Celular (tim): (19) 8177-5725
Escritório: (11) 3230-9233
 empreendemia.com.br http://www.empreendemia.com.br/ - a rede de empresas
para acelerar seus negócios
 saiadolugar.com.br http://www.saiadolugar.com.br/ - dicas para o
empreendedor que não tem tempo a perder
"Até mais, e obrigado pelos peixes!" - Guia do Mochileiro das Galáxias

Em 11 de junho de 2013 17:25, mauro0x52 notifications@github.com escreveu:

**Comment by rerthal** [comment]
arranquei fora o kamisama

**Comment by millor** [comment]
Ao remover nota de uma tarefa ela não aparece na listagem, precisa refrescar

**Comment by rerthal** [comment]
o que é nota de uma tarefa? esse campo não existe...

**Comment by rerthal** [comment]
descobri hehehe resolvendo aqui

**Comment by millor** [comment]
Observação, escrevi errado. Foi mal

**Comment by rerthal** [comment]
ja ta resolvido

Rafael Almeida Erthal
Hermanohttp://www.google.com/url?q=http%3A%2F%2Fwww.empreendemia.com.br&sa=D&sntz=1&usg=AFQjCNEOHUWi5cAicdE_YNDRultw-a6Kaw
Stormtrooper
Celular (Tim): (19) 8139-5432
empreendemia.com.br http://www.empreendemia.com.br - a rede de empresas
para acelerar seus negócios
 saiadolugar.com.br http://www.saiadolugar.com.br - dicas para o
empreendedor que não tem tempo a perder
"Execute order 66" - Chancellor Palpatine

_Ressalva Legal_

_Esta mensagem pode conter informação confidencial ou privilegiada, sendo
seu sigilo protegido por lei. Se você não for o destinatário ou a pessoa
autorizada a receber esta mensagem, não pode usar, copiar ou divulgar as
informações nela contidas ou tomar qualquer ação baseada nessas
informações. Se você recebeu esta mensagem por engano, por favor, avise
imediatamente ao remetente, respondendo o e-mail e em seguida
apague-a. *_Agradecemos
sua cooperação.*
- *

_Legal Reminder_
_This message may contain confidential or privileged information and its
confidentiality is protected by law. If you are not the addressed or
authorized person to receive this message, you must not use, copy, disclose
or take any action based on it or any information herein. If you have
received this message by mistake, please advise the sender immediately by
replying the e-mail and then deleting it. Thank you for your cooperation._

2013/7/10 millor notifications@github.com

**Comment by millor** [comment]
Ao remover observação de um contato ele não aparece na listagem, precisa refrescar
