### ISSUE TITLE
Salvar quebra de linha no campos 'observações'

### ISSUE THREAD

**Issue by mineirocosta** [mauro0x52/eekit#256]
Caso: Ao editar o campo **observações** de uma tarefa, contato ou transação com várias linhas, a quebra de linha não é salva e as linhas ficam todas juntas.

_Como eu escrevo:_
**Observações:**
contrato dura 2 meses
muito interessado no produto

_Como fica após salvar:_
**Observações:**
contrato dura 2 mesesmuito interessado no produto

**Comment by mauro0x52** [comment]
O ajax não está enviando \n.
