### ISSUE TITLE
Orientador desconfigurado no novo eekit

### ISSUE THREAD

**Issue by mineirocosta** [mauro0x52/eekit#257]
**Bug em todos os apps (tarefas, contatos e finanças)**
Orientador não desaparece após ação recomendada por ele ser feita 
Ex: No tarefas, orientador recomenda adicionar tarefa. Ao clicar e adicionar uma tarefa o orientador continua na tela.

**Bug app contatos**
Situação: ao adicionar o primeiro contato, a entidade desse contato abre automaticamente
Problema: ao abrir a entidade, não abre a mensagem do orientador instruindo  o usuário a adicionar uma nova tarefa para aquele contato

**Comment by mauro0x52** [comment]
O primeiro consegui resolver. 

O segundo tem pica de SDK.
@rafaelalmeidaerthalhermano resolve ae.

**Comment by millor** [comment]
Vou fechar essa issue e criar outra só com o 2o bug, sem estar associada ao milestone "Novo sdk" para não travar o deploy
