### ISSUE TITLE
Esqueci minha senha

### ISSUE THREAD

**Issue by mauro0x52** [mauro0x52/eekit#26]
Workflow
- Clicar em "esqueci minha senha"
- Preencher email
- Receber email de resetar senha (dar prazo de 1h) e clica no link
- Cair na tela /usuarios

**Comment by millor** [comment]
Testei em Pelúcio e me mandou pra AWS: http://www.empreendekit.com.br/?token=96f736761db7eefd88b31985ed38a91564a0f2b70263819a8c8331e501dcb7210918b117f32dcc40965894e4224becaa49e7f65584a835e4da26977902c49069#!/ee/usuarios

Era esse o comportamento esperado?

**Comment by mauro0x52** [comment]
É só trocar a url

**Comment by mauro0x52** [comment]
no caso http://www.empreendemia.no-ip.org:8000/?token=96f736761db7eefd88b31985ed38a91564a0f2b70263819a8c8331e501dcb7210918b117f32dcc40965894e4224becaa49e7f65584a835e4da26977902c49069#!/ee/usuarios

**Comment by millor** [comment]
Tá caindo logado na página /usuarios, mas sem abrir o modal de alterar a senha
