### ISSUE TITLE
Lembretes só aparece ao adicionar tarefa com data já setada

### ISSUE THREAD

**Issue by millor** [mauro0x52/eekit#260]
Ao adicionar tarefas pelo botão no topo da listagem ou através da entidade de um contato os campos de adição de lembretes não aparecem no modal. 

Funciona quando edito a tarefa ou quando adiciono direto pelo dia.

Também não funciona quando edito tarefa que foi salva sem prazo. 

Tudo indica que tem a ver com o modal abrir já com a data definida anteriormente

**Comment by mauro0x52** [comment]
Isso já acontece com o empreendekit atualmente no ar. De qualquer forma vou tentar corrigir.

**Comment by mauro0x52** [comment]
Desencana, entendi a pica.

**Comment by millor** [comment]
Mantenho isso associado ao deploy ou melhor deixar como backlog?

**Comment by mauro0x52** [comment]
Resolvi
