### ISSUE TITLE
Exportação do Contatos não obedecendo o filtro

### ISSUE THREAD

**Issue by luizpiovesana** [mauro0x52/eekit#265]
A exportação do Contatos não está levando em consideração o filtro.

Além disso, ele não está exportando as categorias dos contatos (o que faz com que fique ainda mais difícil trabalhar os dados no excel).

**Comment by rerthal** [comment]
TESTA AE!!

**Comment by luizpiovesana** [comment]
Exportação já está obedecendo o filtro -- esta parte ok.

Outros problemas da exportação:
- O campo "categoria" está com o conteúdo "undefined" para todos os contatos. 
- o campo "email" está vindo com o conteúdo do campo "telefone" (ou seja, na coluna de telefone e na coluna de email aparecem os telefones -- tá duplicado)
- Os campos personalizados estão todos confusos: o campo "último contato em" foi engolido pelo campo "URL tracker", assim como no campo "produto ou serviço" apareceram as 'datas de última contato' -- acho que é uma questão de ordem só
- O campo "Observações" não foi exportado -- nem o título lá em cima tem

Segue aqui o csv para observação: https://www.dropbox.com/s/oxfvqia2q2sujyt/download%20%286%29.csv
