### ISSUE TITLE
Página de "não funfamos no IE"

### ISSUE THREAD

**Issue by mauro0x52** [mauro0x52/eekit#269]

**Comment by mauro0x52** [comment]
@rafaelalmeidaerthalhermano  tenta dar uma prioridade pra isso, beleuza?

**Comment by rerthal** [comment]
Okie dokie
Em 10/06/2013 10:20, "mauro0x52" notifications@github.com escreveu:

**Comment by rerthal** [comment]
resolvido

**Comment by luizpiovesana** [comment]
Ficou assim:

![image](https://f.cloud.github.com/assets/3373012/649668/01c2fd86-d44a-11e2-819f-9ed2fa5ce9b4.png)

**Comment by luizpiovesana** [comment]
O pessoal aqui pediu para colocar como opção "Firefox ou Google Chrome".

**Comment by rerthal** [comment]
isso aqui ja não esta resolvido?

**Comment by millor** [comment]
Aparentemente não. Na última vez a engrenagem ficava girando e nada acontecida

**Comment by rerthal** [comment]
eu olhei o código agora, e parece que o mauro ja fez as correções, só faltou o cabeça revalidar... depois da uma olhada com ele... ou então é alguma pica de css no ie pq no ff e no chrome a engrenagem não aparece e o chrome ja está sendo sugerido

**Comment by millor** [comment]
Vou caçar um computador com IE aqui em casa e já testo isso
