### ISSUE TITLE
Botões de pagamento

### ISSUE THREAD

**Issue by mauro0x52** [mauro0x52/eekit#271]
Meter os botões de pagamento na página de pagamentos

**Comment by millor** [comment]
"Plano de 6 meses" precisa mudar para "Plano de 12 meses"

**Comment by mauro0x52** [comment]
Isso não havia sido especificado.

**Comment by mauro0x52** [comment]
Coloca os dados e valores aí certinho de como tem que ir.

**Comment by millor** [comment]
O botão e o valor estão certos, é só mudar o texto "Plano 6 meses" pra "Plano 12 meses".

Uma parada bem relevante que esquecemos é adicionar a linha "Emita boletos" na caixa ferramentas

**Comment by mauro0x52** [comment]
Boletos enquanto não tiver redondo é melhor não divulgamos tanto.

**Comment by millor** [comment]
Show, coloquei de backlog pra usarmos isso no material de vendas mais pra frente. Issue aprovada, to fechando aqui.
