### ISSUE TITLE
Email de Lifecycle Engajamento 4 - Tarefas (3)

### ISSUE THREAD

**Issue by lucashoogerbrugge** [mauro0x52/eekit#274]
Lifecycle  Engajamento 4 - Tarefas

**Regra para receber o email:**
*Usuário não engajado depois de 96h de ativar no tarefas
*Só recebe email se não tiver recebido: 
--Lifecycle  Engajamento 4 -  Contatos
--Lifecycle  Engajamento 4 -  Finanças

(futuramente usuário pagante não receberá esse email, mas essa regra ainda não se aplica)

**Source:** eekit
**Medium:** email
**Campaign:** lifecycle
**Content:** engajamento-4t
**Nome no sendgrid:** eekit lc engajamento 4t
**Responder para:** gabriel@empreendemia.com.br
**UTM:** http://www.empreendekit.com.br/?utm_source=eekit&utm_medium=email&utm_content=engajamento-4t&utm_campaign=lifecycle#!/tarefas

**Assunto:** Recursos legais do EmpreendeKit que você pode não ter visto ainda

**Conteúdo:** 
Olá _|FNAME|_, tudo bom?

Você chegou a ver nossos lembretes por email no EmpreendeKit?

Enviaremos o lembrete diretamente para seu email para você não se preocupar mais em esquecer de fazer alguma tarefa.

É só adicionar uma tarefa com data e clicar em "Mais informações".
Depois disso é só clicar no período que você deseja ser lembrado.

Para acessar o EmpreendeKit e configurar seus lembretes, é só clicar aqui.

Abraços,
Gabriel

**Comment by mauro0x52** [comment]
Lucas quem vai enviar.

**Comment by mauro0x52** [comment]
Não é mais empreendekit.com.br/#!/tarefas, é empreendekit.com.br/tarefas.

**Comment by mauro0x52** [comment]
não vai rolar o critério se ele recebeu email dos lifecycles de contatos e finanças

**Comment by mauro0x52** [comment]
Mudança do critério:
- usuário = ativo no tarefas há 4 dias
- usuário != ativo no contatos
- usuário != ativo no finanças
