### ISSUE TITLE
Drag n' drop muito doido quando entidade tem observação que ocupa mais de uma linha

### ISSUE THREAD

**Issue by millor** [mauro0x52/eekit#280]
Ao arrastar uma tarefa ou contato para posição de uma entidade com pelo menos 2 linhas de observações (quanto mais linhas, pior), a posição fica oscilando muito rapidamente

Tenho banco de dados em Pelúcio para reproduzir facilmente a situação, qualquer coisa é só me chamar

**Comment by rerthal** [comment]
escondi a observações enquanto o dnd esta ativo
