### ISSUE TITLE
Atualizar emails de Pagamento

### ISSUE THREAD

**Issue by lucashoogerbrugge** [mauro0x52/eekit#281]
**L.C. Geral 1 - Seu período de test-dive está acabando. Você tem alguma dúvidas?**

**Regra para receber o email:**
- Usuário recebe e-mail (240h) 5 dias antes de terminar o test-drive

**Source:** eekit
**Medium:** email
**Campaign:** lifecycle
**Content:** geral-1
**Nome no sendgrid:** eekit lc geral 1
**Responder para:** lucas@empreendemia.com.br

**Assunto:** Seu período de testes do EmpreendeKit acaba em 5 dias

**Conteúdo:** Olá _|FNAME|_, tudo bom?

Estou mandando este e-mail porque o seu período de testes do EmpreendeKit está terminando. 

Existe alguma forma que posso te ajudar, ou sanar alguma dúvida?

Abraços
Lucas

**L.C. Geral 2 - Seu test-drive acabou. Paga ai maluco!**

**Regra para receber o email:**
- Usuário recebe e-mail (360h) no dia de termino do test-drive com botão de pagamento

**Source:** eekit
**Medium:** email
**Campaign:** lifecycle
**Content:** geral-2
**Nome no sendgrid:** eekit lc geral 2
**Responder para:** lucas@empreendemia.com.br
**UTM:** http://www.empreendekit.com.br/?utm_source=eekit&utm_medium=email&utm_content=geral-2&utm_campaign=lifecycle/ee/precos-e-planos

**Assunto:** Fim do seu teste no EmpreendeKit

**Conteúdo:** Olá _|FNAME|_, tudo bom?

O seu período de testes acabou, mas não precisa ser assim!
Você pode ativar o EmpreendeKit fazendo o pagamento de R$59,90 mensais (que você só paga no mês que usar).

Para isso, é só clicar no botão abaixo.
-botão de assinatura 59,90-

Se ainda tiver alguma dúvida e quiser falar conosco, é só me responder ou entrar em contato através de um dos canais abaixo, que ficaremos felizões de te atender. Eventualmente podemos até estender seu teste.
Você pode entrar em contato comigo por esse email, ou pelo telefone: (11) 3230-9233.

Se você quiser, também temos outros planos para períodos maiores com um desconto bacana.
Para acessar nossa página de planos, é só clicar aqui.

Abraços
Lucas

**Comment by mauro0x52** [comment]
@lucashoogerbrugge  Põe labels e milestone, seu safado.
