### ISSUE TITLE
Tarefa recorrente marcada como feita aparece na lista embedada de outros usuários da mesma empresa

### ISSUE THREAD

**Issue by millor** [mauro0x52/eekit#283]
Usuário A e usuário B são da mesma empresa. 

Caso de erro:
- Usuário A abre ficha de um contato
- Usuário B marca uma tarefa recorrente como feita
- Usuário B visualiza a nova tarefa com o prazo futuro
- Usuário A visualiza a nova tarefa com o prazo futuro dentro da ficha do contato, mesmo que não tenha nada a ver com o contato

**Comment by rerthal** [comment]
Vou arrancar fora o kami-sama, to eekit

**Comment by millor** [comment]
Testei o caso de uso e funfou. Vou fechar a issue
