### ISSUE TITLE
Recuperação de senha no EmpreendeKit está case sensitive

### ISSUE THREAD

**Issue by lucashoogerbrugge** [mauro0x52/eekit#285]
Como usuário, gostaria que a recuperação de email no EmpreendeKit não fosse case sensitive

**Comment by rerthal** [comment]
acho que isso pode deixar brechas para alguns problemas, sou a favor de manter case-sensitive? alguém discorda?

**Comment by millor** [comment]
Melhor manter case sensitive mesmo. Não vale a pena o esforço de ficar fazendo as verificações. Estou dando wontfix e fechando a issue
