### ISSUE TITLE
Estatísticas do usuário

### ISSUE THREAD

**Issue by mauro0x52** [mauro0x52/eekit#286]
Levantar estatísticas do usuário para aumentar a eficiência do tracker e implementar os lifecycles.

**Comment by mauro0x52** [comment]
Para testar, empreendemia.no-ip.org:8003/statistics e a senha

**Comment by lucashoogerbrugge** [comment]
Alguns bugs

1 - Ao cadastrar usuário e acessar app, não está aparecendo o usuário na listagem
2- Quando adicionei uma tarefa, usuário que não tinha aparecido ainda apareceu já ativado
3- Ao marcar 3 tarefas (critério de engajamento), usuário fica com status new
4- Ao adicionar receita no finanças, não aparece como ativado
5- Estava com status new no tarefas(caso 3), engaged no finanças e no contatos, ai adicionei uma tarefa no tarefas e o status do tarefas ficou engaged, active no finanças e no contatos
6- Depois do caso 5 adicionei um contato no contatos e o status do finanças e do contatos ficou como engaged e do tarefas como active
