### ISSUE TITLE
Date picker não deixa selecionar mês seguinte

### ISSUE THREAD

**Issue by luizpiovesana** [mauro0x52/eekit#293]
Durante a última semana do mês, o date picker do inserir tarefa não deixa você escolher um dia da semana seguinte (a 1ª do próximo mês).

Ao mesmo tempo, ao mudar o mês primeiro e depois escolher o dia, algumas vezes a data acaba não sendo alterada.

Isso acontece nos date pickers do 'inserir tarefas' que não vem com a data preenchida - tanto dentro do Tarefas, sem data, quanto dentro de um contato.

**Comment by millor** [comment]
No Firefox está funcionando normal. Aparentemente é algum problema com o Chrome no Windows

**Comment by luizpiovesana** [comment]
Só pra deixar mais específico:
quando clico na semana seguinte (julho, nesse caso), o date picker some, mas nenhuma data aparece.

No caso de mudar o mês antes, ele acaba selecionando o dia 25/jul como default, mas ao clicar em qualquer outro dia acontece a mesma coisa: o date picker some e a data continua como 25/7

**Comment by rerthal** [comment]
não estou conseguindo reproduzir o bug, o que complica um bocado a vida....

**Comment by millor** [comment]
Aparentemente parou de dar o problema com a remoção do Kami-sama. Estou dando wontfix e fechando
