### ISSUE TITLE
Trocar emails para Millor

### ISSUE THREAD

**Issue by mauro0x52** [mauro0x52/eekit#294]
Trocar todos os emails de lifecycle para millor.

**Comment by millor** [comment]
No e-mail "Preparamos uma Consultoria para te ajudar a ser mais produtivo com o EmpreendeKit" a assinatura tá como Abraços, Lucas

**Comment by millor** [comment]
Tem também o e-mail de novo usuário, que atualmente é mandado pra Lucas

**Comment by millor** [comment]
No e-mail "Lifecycle Geral 1", com título "Seu período de testes do EmpreendeKit acaba em 5 dias", a assinatura também está como Lucas

**Comment by millor** [comment]
Precisa também trocar no "2 dicas fáceis para cuidar dos prazos de seus clientes"

**Comment by millor** [comment]
Também no "Agora falta pouco para se tornar um mestre da produtividade!" relacionado ao finanças
