### ISSUE TITLE
Usuários não conseguem cadastrar

### ISSUE THREAD

**Issue by millor** [mauro0x52/eekit#295]
Já recebi uns 4 e-mails de usuários falando que tentam cadastrar e a tela fica preta, sem voltar pra tela inicial.

Não consegui reproduzir em Pelúcio. Qual a melhor forma de identificar se o cadastro do cara foi feito ou não? Como faço pra rastrear os casos em que esse bug acontece?

**Comment by rerthal** [comment]
será que esses usuarios estão usando o IE? o ideal seria eles enviarem o log de erros no log do firebug(muito complexo para eles) tenta arrumar um printscream pelo menos

**Comment by millor** [comment]
Provavelmente era quando o sistema caía. Vou fechar a issue por enquanto como wontfix e depois vemos se o problema volta sem o kami-sama
