### ISSUE TITLE
Lista de usuários

### ISSUE THREAD

**Issue by millor** [mauro0x52/eekit#297]
Como admin gostaria de saber a lista dos usuários cadastrados no sistema e seus respectivos ids

**Comment by rerthal** [comment]
voce pode usar o próprio auth para isso,
na url : :8001/users?secret=
voce deve apenas pegar o secret do auth que esta no config na amazon com o mauro e esta resolvido =) 
em pelucio é só acessar: http://empreendemia.no-ip.org:8001/users?secret=auth

**Comment by millor** [comment]
Isso já tá no ar e dependo só do secret ou precisa dar o deploy junto com as outras alterações?

**Comment by rerthal** [comment]
Ja ta no ar
Em 10/07/2013 17:39, "millor" notifications@github.com escreveu:
