### ISSUE TITLE
Exportação do Financeiro ignorando alguns valores

### ISSUE THREAD

**Issue by luizpiovesana** [mauro0x52/eekit#301]
Exportei nosso financeiro de junho/2013 e, ao ver que o saldo não bateu, conferi dia a dia as transações.
Com isso, vi que das 12 transações do dia 20, só 9 foram exportadas; e das 8 transações do dia 28, só 7 foram exportadas.

Não conseguimos achar um padrão de texto das transações ou mesmo do número de transações no dia. O único padrão é que estas transações estão nos primeiros lugares em seus dias.

Pensei em ser o número de transações por dia, o dia 3 tem 8 transações e todas apareceram.

As transações não exportadas fora:
20/6 - INSS Sócios (165,00)
20/6 - INSS Sócios (330,00)
20/6 - Escritório (173,84)
28/6 - AWS

**Comment by millor** [comment]
Considerando que conseguimos resolver razoavelmente fácil na mão e deve problema ser cabeludo, não vale a pena se stressar pra fuçar a causa do bug. Estou dando won't fix e fechando
