### ISSUE TITLE
Aceitar 9 dígitos no campo telefone

### ISSUE THREAD

**Issue by millor** [mauro0x52/eekit#302]
Como usuário de São Paulo gostaria de poder cadastrar meu telefone com 9 dígitos no Empreendekit para receber ligações dos admin

**Comment by mauro0x52** [comment]
Já é possível cadastrar telefones com 9 dígitos. Que formato vc tentou?

**Comment by millor** [comment]
Testei de novo e funfou. Não lembro qual formato tinha colocado. Vou dar wont fix e fechar
