### ISSUE TITLE
Data de cadastro dos usuários

### ISSUE THREAD

**Issue by mauro0x52** [mauro0x52/eekit#306]
Não está pegando a data certa do cadastro do usuário.

**Comment by mauro0x52** [comment]
Alguns lifecycles dependiam desta data então muito provavelmente não estavam funcionando direito. Dentre eles:
- lc_ativacao_2
- lc_ativacao_3
- lc_ativacao_4
- lc_geral_1
- lc_geral_2
- lc_nutricao_1

**Comment by millor** [comment]
Dos que você mandou, lc_ativação realmente estavam com problema. lc_geral e lc_nutricao teoricamente estavam funcionando já.

Pelo Sendgrid, os de ativação ainda não foram enviados. Mas também não sei dizer se tiveram usuários que atingiram o critério
