### ISSUE TITLE
Acentuação do arquivo exportado no Finanças

### ISSUE THREAD

**Issue by luizpiovesana** [mauro0x52/eekit#32]
Dois problemas:
- A acentuação no financeiro vem com aqueles símbolos
- No nome da transação, quando tem recorrência e aparece a parcela (tipo 3/5) E quando é um nome composto, não tá rolando espaço entre as palavras ou mesmo com o número.

De resto tá tranquilo.

**Comment by luizpiovesana** [comment]
A exportação do Finanças continua com acentuação e espaços zuados.

Inclusive, rola tirar o cifrão "$" do arquivo exportado. Lá ele só atrapalha, então se a pessoa não manjar de excel, vai ter trabalho.

**Comment by rerthal** [comment]
deployado

**Comment by luizpiovesana** [comment]
Tá muito bom.
Para fazer em breve:
- Tirar o cifrão
- Exportar com vírgula ao invés do ponto como separador do decimal

**Comment by luizpiovesana** [comment]
O cifrão ainda tá aparecendo.

O ponto eu já fui informado que não rola tirar.
