### ISSUE TITLE
Exportação de dados do Contatos

### ISSUE THREAD

**Issue by rerthal** [mauro0x52/eekit#37]
Exportar campos personalizados dos contatos

**Comment by luizpiovesana** [comment]
Não rolou.
Erros:
- Nas primeiras 3 tentativas, ela só exportava o único contato antigo. Depois que eu editei esse contato antigo, os demais começaram a aparecer no arquivo exportado.
- Acentuação e espaços com problemas
- Campos personalizados não são exportados.

**Comment by rerthal** [comment]
deployado

**Comment by luizpiovesana** [comment]
Funciona direitinho, mas precisa atualizar (F5) a página antes, se não exporta só os dados antigos.
