### ISSUE TITLE
Surge uma receita 'não cadastrada' no Finanças

### ISSUE THREAD

**Issue by mineirocosta** [mauro0x52/eekit#39]
No Finanças, ao usar a data inicial do filtro maior que 22/02, surge uma diferença de R$3333,00 (receita).

usuário: gabriel@empreendemia.com.br
id: 506ae51f8276f82e39000004

**Comment by rerthal** [comment]
provavelmente esse bug é decorrente de um dado antigo do banco de dados... caso ele apareça novamente, voltar a reporta-lo
