### ISSUE TITLE
Initial Refer no Tracker

### ISSUE THREAD

**Issue by lucashoogerbrugge** [mauro0x52/eekit#41]
Varrer eventos do usuário sem filtragem de app para pegar utm, depois fazer filtragem normal

**Comment by lucashoogerbrugge** [comment]
Como eu testo isso? Tem um tracker do pelucio?

**Comment by rerthal** [comment]
sim tem um empreendemia.no-ip.org:8003/events

**Comment by lucashoogerbrugge** [comment]
Teste no Pelucio e quando tiro o utm e entro com a mesma conta perde o initial refer no tracker.
Era pra ser assim mesmo @rafaelalmeidaerthalhermano ?
Pode ser algo a ver com aquele bug de aparecer deslogado, mesmo estando logado?
