### ISSUE TITLE
Tarefas: Visualização de tarefas de um cliente na entidade

### ISSUE THREAD

**Issue by millor** [mauro0x52/eekit#5]
Fluxo:
- Selecionar uma tarefa relacionada a um cliente
- Clicar no nome do cliente
- Visualização de tarefas pendentes e feitas do cliente está em branco

A tarefa está sendo adicionada corretamente, só a listagem na entidade que não mostra nada.

**Comment by luizpiovesana** [comment]
As tarefas relacionadas (tanto pendentes quanto já feitas) ao contato também não aparecem acessando a entidade dentro do Contatos
