### ISSUE TITLE
Excluir apenas as movimentações com datas maiores ou iguais as datas da exclusão do contato

### ISSUE THREAD

**Issue by rerthal** [mauro0x52/eekit#63]
Como usuário gostaria que ao excluir contato, o sistema excluisse apenas as movimentações com datas maiores ou iguais a data da exclusão do contato

**Comment by millor** [comment]
A princípio tinha sido pensado como mesmo dia também sendo excluído, mas chegamos à conclusão de que não tem problema manter a movimentação do dia
