### ISSUE TITLE
Filtragem de data no tracker

### ISSUE THREAD

**Issue by millor** [mauro0x52/eekit#85]
Como admin gostaria de filtrar datas do Tracker para facilitar minha análise e reduzir o número de eventos exibidos pelo servidor

Seria bacana um formato do tipo:
http://empreendemia.no-ip.org:8003/events/16-03-2013/19-03-2013

As datas limite da filtragem estão incluídas nos eventos, intervalo fechado

Os dados continuam sendo exibidos da mesma forma, inclusive com o UTM nas colunas

**Comment by rerthal** [comment]
o formato será 
/events?from=2013-03-18&to=2013-03-20
sendo o intervalo de datas: [from, to[
